Fix compile error on ubuntu 20.04.1 LTS
In the ubuntu 20.04.1 LTS environment, the compilation fails because
the header file <sys/sysmacros.h> of the major min function is not
referenced. This patch fixes it.

Message as follows:
-------------------------------------------------------------------
make  all-recursive
make[1]: Entering directory '/root/src/f2fs-tools2'
Making all in man
make[2]: Entering directory '/root/src/f2fs-tools2/man'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/root/src/f2fs-tools2/man'
Making all in lib
make[2]: Entering directory '/root/src/f2fs-tools2/lib'
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -Wall -g -O2 -MT libf2fs_la-libf2fs.lo -MD -MP -MF .deps/libf2fs_la-libf2fs.Tpo -c -o libf2fs_la-lc
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -Wall -g -O2 -MT libf2fs_la-libf2fs.lo -MD -MP -MF .deps/libf2fs_la-libf2fs.Tpo -c libf2fs.c  -fPIC -DPIC -o .libs/libf2fs_la-libo
libf2fs.c: In function ‘get_rootdev’:
libf2fs.c:534:3: warning: implicit declaration of function ‘major’ [-Wimplicit-function-declaration]
  534 |   major(sb.st_dev), minor(sb.st_dev));
      |   ^~~~~
libf2fs.c:534:21: warning: implicit declaration of function ‘minor’ [-Wimplicit-function-declaration]
  534 |   major(sb.st_dev), minor(sb.st_dev));
      |                     ^~~~~
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -Wall -g -O2 -MT libf2fs_la-libf2fs.lo -MD -MP -MF .deps/libf2fs_la-libf2fs.Tpo -c libf2fs.c -o libf2fs_la-libf2fs.o >/dev/null 21
mv -f .deps/libf2fs_la-libf2fs.Tpo .deps/libf2fs_la-libf2fs.Plo
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -Wall -g -O2 -MT libf2fs_la-libf2fs_io.lo -MD -MP -MF .deps/libf2fs_la-libf2fs_io.Tpo -c -o libf2fc
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -Wall -g -O2 -MT libf2fs_la-libf2fs_io.lo -MD -MP -MF .deps/libf2fs_la-libf2fs_io.Tpo -c libf2fs_io.c  -fPIC -DPIC -o .libs/libf2o
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -Wall -g -O2 -MT libf2fs_la-libf2fs_io.lo -MD -MP -MF .deps/libf2fs_la-libf2fs_io.Tpo -c libf2fs_io.c -o libf2fs_la-libf2fs_io.o 1
mv -f .deps/libf2fs_la-libf2fs_io.Tpo .deps/libf2fs_la-libf2fs_io.Plo
/bin/bash ../libtool  --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I..  -I../include  -Wall -g -O2 -MT libf2fs_la-libf2fs_zoned.lo -MD -MP -MF .deps/libf2fs_la-libf2fs_zoned.Tpo -c -o c
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -Wall -g -O2 -MT libf2fs_la-libf2fs_zoned.lo -MD -MP -MF .deps/libf2fs_la-libf2fs_zoned.Tpo -c libf2fs_zoned.c  -fPIC -DPIC -o .lo
libtool: compile:  gcc -DHAVE_CONFIG_H -I. -I.. -I../include -Wall -g -O2 -MT libf2fs_la-libf2fs_zoned.lo -MD -MP -MF .deps/libf2fs_la-libf2fs_zoned.Tpo -c libf2fs_zoned.c -o libf2fs_la-libf1
mv -f .deps/libf2fs_la-libf2fs_zoned.Tpo .deps/libf2fs_la-libf2fs_zoned.Plo
/bin/bash ../libtool  --tag=CC   --mode=link gcc -Wall -g -O2 -version-info 3:0:0  -o libf2fs.la -rpath /usr/local/lib libf2fs_la-libf2fs.lo libf2fs_la-libf2fs_io.lo libf2fs_la-libf2fs_zoned
libtool: link: gcc -shared  -fPIC -DPIC  .libs/libf2fs_la-libf2fs.o .libs/libf2fs_la-libf2fs_io.o .libs/libf2fs_la-libf2fs_zoned.o    -g -O2   -Wl,-soname -Wl,libf2fs.so.3 -o .libs/libf2fs.s0
libtool: link: (cd ".libs" && rm -f "libf2fs.so.3" && ln -s "libf2fs.so.3.0.0" "libf2fs.so.3")
libtool: link: (cd ".libs" && rm -f "libf2fs.so" && ln -s "libf2fs.so.3.0.0" "libf2fs.so")
libtool: link: ar cr .libs/libf2fs.a  libf2fs_la-libf2fs.o libf2fs_la-libf2fs_io.o libf2fs_la-libf2fs_zoned.o
libtool: link: ranlib .libs/libf2fs.a
libtool: link: ( cd ".libs" && rm -f "libf2fs.la" && ln -s "../libf2fs.la" "libf2fs.la" )
make[2]: Leaving directory '/root/src/f2fs-tools2/lib'
Making all in mkfs
make[2]: Entering directory '/root/src/f2fs-tools2/mkfs'
gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/include/uuid -I/usr/include/blkid -I../include  -Wall -DWITH_BLKDISCARD -g -O2 -MT f2fs_format_main.o -MD -MP -MF .deps/f2fs_format_main.Tpo -c -o f2fs_fc
mv -f .deps/f2fs_format_main.Tpo .deps/f2fs_format_main.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/include/uuid -I/usr/include/blkid -I../include  -Wall -DWITH_BLKDISCARD -g -O2 -MT f2fs_format.o -MD -MP -MF .deps/f2fs_format.Tpo -c -o f2fs_format.o f2c
f2fs_format.c: In function ‘f2fs_prepare_super_block’:
f2fs_format.c:380:18: warning: taking address of packed member of ‘struct f2fs_super_block’ may result in an unaligned pointer value [-Waddress-of-packed-member]
  380 |  utf8_to_utf16(sb->volume_name, (const char *)c.vol_label,
      |                ~~^~~~~~~~~~~~~
mv -f .deps/f2fs_format.Tpo .deps/f2fs_format.Po
gcc -DHAVE_CONFIG_H -I. -I..  -I/usr/include/uuid -I/usr/include/blkid -I../include  -Wall -DWITH_BLKDISCARD -g -O2 -MT f2fs_format_utils.o -MD -MP -MF .deps/f2fs_format_utils.Tpo -c -o f2fsc
mv -f .deps/f2fs_format_utils.Tpo .deps/f2fs_format_utils.Po
/bin/bash ../libtool  --tag=CC   --mode=link gcc -Wall -DWITH_BLKDISCARD -g -O2   -o mkfs.f2fs f2fs_format_main.o f2fs_format.o f2fs_format_utils.o -luuid -lblkid ../lib/libf2fs.la
libtool: link: gcc -Wall -DWITH_BLKDISCARD -g -O2 -o .libs/mkfs.f2fs f2fs_format_main.o f2fs_format.o f2fs_format_utils.o  -luuid -lblkid ../lib/.libs/libf2fs.so
/usr/bin/ld: ../lib/.libs/libf2fs.so: undefined reference to `minor'
/usr/bin/ld: ../lib/.libs/libf2fs.so: undefined reference to `major'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:487: mkfs.f2fs] Error 1
make[2]: Leaving directory '/root/src/f2fs-tools2/mkfs'
make[1]: *** [Makefile:415: all-recursive] Error 1
make[1]: Leaving directory '/root/src/f2fs-tools2'
make: *** [Makefile:347: all] Error 2

Signed-off-by: Yuanliang Wang <wangyuanliang@bytedance.com>